# Generated by Django 4.2.9 on 2024-01-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexresearch', '0003_userlogin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlogin',
            options={},
        ),
        migrations.AlterModelTable(
            name='userlogin',
            table=None,
        ),
    ]
