# Generated by Django 4.2.9 on 2024-01-21 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lexresearch', '0004_alter_userlogin_options_alter_userlogin_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
